pipeline {
    agent any
    environment {
        INSTAGRAM_NERIO = '@Nerio'
    }
    stages {
        stage('Greeting') {
            steps {
                echo 'Hello world'
            }
        }
        stage("Print environment variables") {
            steps {
                sh "echo ${env.INSTAGRAM_NERIO}" 
                sh "echo ${INSTAGRAM_NERIO}"
            }
        }
    }
}
